### ISSUE TITLE
GitHub Action failed on git command

### ISSUE THREAD

**Issue by AArnott** [becheran/mlc#97]
**Describe the bug**

GitHub Action fails when run on ubuntu with git-related switches.

**To Reproduce**

I just added this to my github workflow:

```yaml
    - name: 🔗 Markup Link Checker (mlc)
      uses: becheran/mlc@v0.19.0
      with:
        args: --gitignore --root-dir .
```

It [errored out](https://github.com/AArnott/Library.Template/actions/runs/12992417433/job/36232209953#step:10:28) stating that:

```
thread 'main' panicked at src/lib.rs:146:6:
Failed to execute 'git' command: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

Is it `git` that is missing, or some path passed to it? I can't see the command line. 

But given the command is running within a docker container, if `mlc` requires `git` the docker image ought to provide it, right?
And if some other directory path is wrong, ... I'm not sure how much room there is in my yaml to have caused that problem.

**Expected behavior**

I expected it to pass, or state errors in my doc files.

**Desktop (please complete the following information):**
 - OS: ubuntu-22.04
 - Browser: N/A
 - Version: mlc 0.19.0
